#!/bin/sh

borrar()
{
  rm -f *.aux *.toc *.log *.out *.lof
}

# Borro el pdf final
rm -f main.pdf

# Borro los archivos temporales
borrar

cd hechoconsl
borrar
cd ../titulo
borrar
cd ../licencia
borrar

cd ..
./makediffs clean

