#!/bin/sh

borrar()
{
  rm -f *.aux *.toc *.log *.out *.lof
}

# Borro el pdf final
rm -f main.pdf

# Borro los archivos temporales
borrar

cd arquitectura
borrar
cd ../descripcion_agente
borrar

cd ..
./makediffs clean
