#!/bin/bash

TEMP=temp123321
OUTPUT=grupo7_etapa1.tar.gz

# (re)compilo la documentación en Latex.
cd etapa1/doc/
	
echo -n Compilando la documentación Latex...
if (! ./compilarPDF > /dev/null); then
	echo Hubo errores.
	exit 1
fi

echo Hecho.

cd ../..

# Creo un directorio temporal y copio allí los archivos por empaquetar
mkdir $TEMP
cp etapa1/arquitectura.png $TEMP
cp etapa1/diagramaDeClases.png $TEMP
cp etapa1/doc/main.pdf $TEMP/documentacion.pdf

cd $TEMP

echo -n Comprimiendo y armando archivo final de entrega...
if (tar -zcf $OUTPUT *); then
	echo Hecho.
else
	echo Hubo errores.
	exit 1
fi

cd ../

mv ${TEMP}/${OUTPUT} .

echo Eliminando directorio temporal...
rm -rf $TEMP

echo Tareas realizadas exitosamente.
